version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - postgres_network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@govone.digital
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    networks:
      - postgres_network
    ports:
      - "15432:80"

  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: my_rabbitmq
    hostname: my-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: my_elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  my_mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    container_name: my-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
        - "27017:27017"
    volumes:
        - ./data:/data/db
  db_mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - mysqldb:/var/lib/mysql
networks:
  postgres_network:
    driver: bridge

volumes:
  postgres_data:
  mysqldb:
